---
- name: Check an extremely senstive thing
  hosts: all
  tasks:
  - name: Log into the server and check that the ping modules returns output
    ansible.builtin.ping:
      data: pong from Ansible
